[package]
name = "user_lib"
version = "0.1.0"
edition = "2021"
buddy_system_allocator = "0.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

